title: Abadan Syakira
email: abadan191205@gmail.com
description: >
  Hii saya adalah Abadan Syakira, saya adalah Mahasiswa Politeknik Negeri Lhokseumawe, Prodi Teknik Informatika.

url: "https://github.com/abadan1912"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

